// JI-Filable — browser half (client plugin bundle).
// GENERATED by scripts/build-client.mjs from this template + lib/drop-logic.js
// — do not edit lib/client.js by hand; edit this file and drop-logic.js.
// The pure decision/store logic is inlined below (from lib/drop-logic.js) so
// the tested module is byte-identical to what runs here.
window.__ModuleLoader__.load({
  id: "ji-filable",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    var React = require("react");

    // ── pure drop-decision + store logic (inlined from lib/drop-logic.js) ──
// JI-Filable — browser drop-decision logic (pure, testable, single source of
// truth). The client bundle inlines these same small functions because the
// module loader only resolves table words, not sibling files; this module is
// what the unit tests pin.

/** The four image media types the built-in attachment flow accepts. */
const IMAGE_WHITELIST = ['image/png', 'image/jpeg', 'image/webp', 'image/gif']

/**
 * Classify a dropped file's MIME type: whitelisted images keep the existing
 * attachment flow; everything else (including svg/tiff/bmp/heic and any
 * non-image type) is taken over by ji-filable.
 * @returns 'pass' | 'take-over'
 */
function classifyFile(fileType) {
  return IMAGE_WHITELIST.includes(fileType) ? 'pass' : 'take-over'
}

/**
 * Build the upload request URL with URL-encoded query parameters.
 * @param {string} sessionId
 * @param {string} name
 */
function buildUploadUrl(sessionId, name) {
  const params = new URLSearchParams()
  if (sessionId !== '') params.set('session', sessionId)
  params.set('name', name)
  return `/ji-filable/files?${params.toString()}`
}

/** Whether a drag event carries files at all (text/html drags pass through). */
function isFileDrag(dataTransfer) {
  return Boolean(dataTransfer) && Array.from(dataTransfer.types).includes('Files')
}

/**
 * Classify a whole dropped batch by MIME types.
 * @param {Array<string>} fileTypes
 * @returns 'all-images' | 'all-others' | 'mixed'
 */
function classifyBatch(fileTypes) {
  const types = Array.from(fileTypes || [])
  if (types.length === 0) return 'all-others'
  const hasImage = types.some(type => IMAGE_WHITELIST.includes(type))
  const hasOther = types.some(type => !IMAGE_WHITELIST.includes(type))
  if (hasImage && hasOther) return 'mixed'
  return hasImage ? 'all-images' : 'all-others'
}

/**
 * Collect the MIME types visible on a DataTransfer before drop. Chrome exposes
 * item.type on dragenter/dragover; when nothing is visible yet the caller must
 * fall back to drop-time classification via dataTransfer.files.
 * @returns {Array<string>}
 */
function dragTypes(dataTransfer) {
  const items = dataTransfer && dataTransfer.items ? Array.from(dataTransfer.items) : []
  return items
    .map(item => (item && typeof item.type === 'string' ? item.type : ''))
    .filter(type => type !== '')
}

/** Human-readable byte size ("1.2 MB"). */
function formatBytes(value) {
  const n = Number(value)
  if (typeof n !== 'number' || !Number.isFinite(n) || n <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB']
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)))
  const v = n / Math.pow(1024, i)
  return `${v >= 100 ? Math.round(v) : v.toFixed(1)} ${units[i]}`
}

/**
 * Minimal subscription store — the single state mechanism behind toasts and
 * chips (one tested implementation, one React bridge).
 * @returns {{get: () => T, set: (next: T) => void, subscribe: (l: (v: T) => void) => () => void}}
 */
function subscribeStore(initial) {
  let value = initial
  const listeners = new Set()
  return {
    get: () => value,
    set(next) {
      value = next
      listeners.forEach(listener => listener(value))
    },
    subscribe(listener) {
      listeners.add(listener)
      return () => { listeners.delete(listener) }
    },
  }
}

/**
 * Plan a dropped batch: split into the files ji-filable takes over and the
 * whitelisted images that keep the existing flow.
 * @param {Array<{type: string}>} files
 * @returns {{takeOver: Array<{type: string}>, skippedImages: number}}
 */
function planUploads(files) {
  const all = Array.from(files || [])
  const takeOver = all.filter(file => classifyFile(file.type) === 'take-over')
  return { takeOver, skippedImages: all.length - takeOver.length }
}

/**
 * Whether ji-filable should show its own drag hint for a visible batch of
 * types: any non-image batch (including mixed) yes; pure whitelisted images no
 * (the composer's image hint covers those). Empty/unknown types fall back to
 * no — the composer's own hint handles them.
 * @param {Array<string>} fileTypes
 * @returns {boolean}
 */
function shouldShowDropHint(fileTypes) {
  const types = Array.from(fileTypes || [])
  if (types.length === 0) return false
  return classifyBatch(types) !== 'all-images'
}

/**
 * Format an `@file` mention for a path under the workspace `sessionfiles/`
 * dir, following the native @-reference grammar: `@path` normally, `@"path"`
 * when the path contains whitespace. Returns null for a path the grammar
 * cannot represent safely (control chars / a stray quote).
 * @param {string} name - the final (deduped) filename on disk.
 * @returns {string | null}
 */
function sessionfilesRef(name) {
  const path = 'sessionfiles/' + String(name)
  if (/[\u0000-\u001f\u007f-\u009f"]/.test(path)) return null
  return /\s/.test(path) ? `@"${path}"` : `@${path}`
}

/**
 * Append a reference to an existing draft, inserting a single space separator
 * only when the draft is non-empty and does not already end in whitespace.
 * @param {string} draft - current composer draft.
 * @param {string} ref - the reference text to append.
 * @returns {string}
 */
function appendRef(draft, ref) {
  const d = String(draft || '')
  const sep = d === '' || /\s$/.test(d) ? '' : ' '
  return d + sep + ref
}

    var NS = "ji-filable";
    var zh = {
      "ji-filable.chip.uploading": "上传中",
      "ji-filable.chip.done": "已就绪",
      "ji-filable.chip.error": "失败",
      "ji-filable.chip.insert": "插入 @地址",
      "ji-filable.chip.close": "关闭",
      "ji-filable.drag.noSession": "请先打开一个会话，再拖入文件",
      "ji-filable.drag.noWorkspace": "无法确定会话工作区，文件未保存",
      "ji-filable.drag.done": "已上传 {count} 个文件到工作区 sessionfiles",
      "ji-filable.drag.mixedDone": "已上传 {count} 个文件（{img} 张图片已跳过，请单独拖入以使用视觉流程）",
      "ji-filable.drag.partial": "上传完成 {ok} 个，失败: {err}",
      "ji-filable.dropHint.title": "拖入文件",
      "ji-filable.dropHint.desc": "松开即保存到工作区 sessionfiles",
      "ji-filable.dropHint.noSession": "先打开一个会话，再拖入文件",
    };
    var en = {
      "ji-filable.chip.uploading": "Uploading",
      "ji-filable.chip.done": "Ready",
      "ji-filable.chip.error": "Failed",
      "ji-filable.chip.insert": "Insert @ref",
      "ji-filable.chip.close": "Close",
      "ji-filable.drag.noSession": "Open a session before dropping files",
      "ji-filable.drag.noWorkspace": "Session workspace unknown — file not saved",
      "ji-filable.drag.done": "Uploaded {count} file(s) to workspace sessionfiles",
      "ji-filable.drag.mixedDone": "Uploaded {count} file(s) ({img} image(s) skipped — drop images alone to use the vision flow)",
      "ji-filable.drag.partial": "Uploaded {ok}, failed: {err}",
      "ji-filable.dropHint.title": "Drop files",
      "ji-filable.dropHint.desc": "Release to save into workspace sessionfiles",
      "ji-filable.dropHint.noSession": "Open a session before dropping files",
    };

    // ── toast store (subscribeStore; timers tracked for fiber cleanup) ─────
    var toasts = subscribeStore([]);
    var toastSeq = 0;
    var pendingTimers = new Set();
    var TOAST_STYLE = { position: "fixed", right: "16px", bottom: "16px", display: "flex", flexDirection: "column", gap: "8px", zIndex: 9999, pointerEvents: "none" };
    var TOAST_ITEM = { padding: "10px 14px", borderRadius: "8px", fontSize: "13px", maxWidth: "320px", boxShadow: "0 4px 16px rgba(0,0,0,.18)", color: "#fff", pointerEvents: "auto" };
    function toast(text, ok) {
      var id = ++toastSeq;
      toasts.set(toasts.get().concat([{ id: id, text: String(text), ok: ok !== false }]));
      var handle = setTimeout(function () {
        pendingTimers.delete(handle);
        toasts.set(toasts.get().filter(function (t) { return t.id !== id; }));
      }, 4000);
      pendingTimers.add(handle);
    }

    // ── chip store (display-only, session-scoped) ──────────────────────────
    var chips = subscribeStore([]);
    var chipSeq = 0;
    var CHIP_ROW_STYLE = { display: "flex", flexWrap: "wrap", gap: "8px", padding: "0 2px 2px", boxSizing: "border-box" };
    var CHIP_ITEM_STYLE = { display: "flex", alignItems: "center", gap: "8px", padding: "6px 10px", borderRadius: "8px", border: "1px solid var(--dsw-alias-border-l2)", background: "var(--dsw-alias-bg-layer-1)", color: "var(--dsw-alias-label-primary)", fontSize: "12px", maxWidth: "320px" };
    var CHIP_ERR_STYLE = { borderColor: "var(--dsw-state-error-primary, #d9534f)" };
    var CHIP_NAME_STYLE = { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" };
    var CHIP_META_STYLE = { color: "var(--dsw-alias-label-secondary)", whiteSpace: "nowrap" };
    var CHIP_DONE_STYLE = { cursor: "pointer" };
    var CHIP_INSERT_STYLE = { marginLeft: "6px", padding: "2px 8px", borderRadius: "6px", border: "1px solid var(--dsw-alias-border-l2)", background: "var(--dsw-alias-bg-layer-2)", color: "var(--dsw-alias-label-primary)", fontSize: "12px", cursor: "pointer", flex: "none" };
    var CHIP_CLOSE_STYLE = { flex: "none", border: "none", background: "transparent", color: "var(--dsw-alias-label-tertiary)", cursor: "pointer", fontSize: "14px", lineHeight: "1", padding: "2px 4px", borderRadius: "4px" };
    var CHIP_CLOSE_HOVER = { background: "var(--dsw-alias-bg-layer-2)", color: "var(--dsw-alias-label-primary)" };
    function addChip(entry) {
      var id = ++chipSeq;
      chips.set(chips.get().concat([Object.assign({ id: id, status: "uploading" }, entry)]));
      return id;
    }
    function updateChip(id, patch) {
      chips.set(chips.get().map(function (chip) { return chip.id === id ? Object.assign({}, chip, patch) : chip; }));
    }
    function clearChips() { chips.set([]); }
    function removeChip(id) {
      chips.set(chips.get().filter(function (chip) { return chip.id !== id; }));
    }

    // ── drop hint store (full-viewport overlay while dragging non-images) ──
    var dropHint = subscribeStore({ visible: false, disabled: false });
    var dropHintDepth = 0;
    var HINT_MASK = { position: "fixed", inset: "0", zIndex: "1000", display: "flex", alignItems: "center", justifyContent: "center", pointerEvents: "none", backgroundColor: "var(--dsw-alias-bg-mask-drop)", backdropFilter: "blur(10px)", animation: "dshHintFade 160ms ease-out" };
    var HINT_WRAP = { display: "flex", flexDirection: "column", alignItems: "center", marginTop: "-3%", padding: "0 40px", color: "var(--dsw-alias-label-primary)", textAlign: "center" };
    var HINT_TITLE = { marginTop: "16px", fontSize: "20px", lineHeight: "28px" };
    var HINT_DESC = { marginTop: "16px", fontSize: "14px", lineHeight: "18px", color: "var(--dsw-alias-label-tertiary)", whiteSpace: "pre-wrap" };
    function showDropHint(disabled) { dropHint.set({ visible: true, disabled: Boolean(disabled) }); }
    function hideDropHint() { dropHintDepth = 0; dropHint.set({ visible: false, disabled: false }); }
    function DropHintOverlay(props) {
      var t = props.t;
      var state = React.useState(dropHint.get());
      var value = state[0];
      var setValue = state[1];
      React.useEffect(function () { return dropHint.subscribe(setValue); }, []);
      if (!value.visible) return null;
      return React.createElement("div", { style: HINT_MASK },
        React.createElement("div", { style: HINT_WRAP },
          value.disabled ? React.createElement(FileIconDisabled, null) : React.createElement(FileIcon, null),
          React.createElement("div", { style: HINT_TITLE }, value.disabled ? t("ji-filable.dropHint.noSession") : t("ji-filable.dropHint.title")),
          value.disabled ? null : React.createElement("div", { style: HINT_DESC }, t("ji-filable.dropHint.desc")),
        ));
    }
    // File-with-upload-arrow icon (theme-neutral tints, distinct from the
    // composer's image-card illustration).
    function FileIcon() {
      return React.createElement("svg", { width: "115", height: "84", viewBox: "0 0 115 84", fill: "none" },
        React.createElement("rect", { x: "26", y: "10", width: "46", height: "54", rx: "9", fill: "#679EFE" }),
        React.createElement("rect", { x: "36", y: "22", width: "26", height: "4", rx: "2", fill: "#fff" }),
        React.createElement("rect", { x: "36", y: "32", width: "26", height: "4", rx: "2", fill: "#fff" }),
        React.createElement("circle", { cx: "74", cy: "56", r: "20", fill: "#9CE5ED" }),
        React.createElement("path", { d: "M74 64V50M69 55l5-5 5 5", stroke: "#fff", strokeWidth: "3", strokeLinecap: "round", strokeLinejoin: "round" }));
    }
    function FileIconDisabled() {
      return React.createElement("svg", { width: "115", height: "84", viewBox: "0 0 115 84", fill: "none" },
        React.createElement("rect", { x: "26", y: "10", width: "46", height: "54", rx: "9", fill: "#979DA6" }),
        React.createElement("rect", { x: "36", y: "22", width: "26", height: "4", rx: "2", fill: "#fff" }),
        React.createElement("circle", { cx: "74", cy: "56", r: "20", fill: "#F59E0B" }),
        React.createElement("path", { d: "M64 46l20 20", stroke: "#fff", strokeWidth: "3.5", strokeLinecap: "round" }));
    }

    function ToastStack(props) {
      var t = props.t;
      var state = React.useState(toasts.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return toasts.subscribe(setItems); }, []);
      return React.createElement("div", { style: TOAST_STYLE },
        items.map(function (item) {
          return React.createElement("div", {
            key: item.id,
            style: Object.assign({}, TOAST_ITEM, { background: item.ok ? "#2f7d4d" : "#c0392b" }),
          }, item.text);
        }));
    }

    // Close (dismiss) button placed at the left edge of a chip. Hover state is
    // tracked per-button so hooks stay inside a stable component (hooks cannot
    // be called inside a .map callback).
    function CloseButton(props) {
      var t = props.t;
      var onRemove = props.onRemove;
      var hover = React.useState(false);
      var isHover = hover[0];
      var setHover = hover[1];
      return React.createElement("button", {
        type: "button",
        "aria-label": t("ji-filable.chip.close"),
        title: t("ji-filable.chip.close"),
        style: Object.assign({}, CHIP_CLOSE_STYLE, isHover ? CHIP_CLOSE_HOVER : {}),
        onMouseEnter: function () { setHover(true); },
        onMouseLeave: function () { setHover(false); },
        onClick: function () { if (onRemove) onRemove(); },
      }, "\u2715");
    }

    function ChipRow(props) {
      var t = props.t;
      var onInsert = props.onInsert;
      var onRemove = props.onRemove;
      var state = React.useState(chips.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return chips.subscribe(setItems); }, []);
      if (items.length === 0) return null;
      return React.createElement("div", { style: CHIP_ROW_STYLE },
        items.map(function (chip) {
          var done = chip.status === "done";
          var statusText = chip.status === "uploading" ? t("ji-filable.chip.uploading") : chip.status === "error" ? t("ji-filable.chip.error") : t("ji-filable.chip.done");
          var rows = [
            React.createElement(CloseButton, { t: t, onRemove: function () { if (onRemove) onRemove(chip.id); } }),
            React.createElement("span", { style: CHIP_NAME_STYLE }, chip.name),
            React.createElement("span", { style: CHIP_META_STYLE }, formatBytes(chip.size) + " · " + statusText),
          ];
          if (done && onInsert) {
            rows.push(React.createElement("button", {
              type: "button",
              style: CHIP_INSERT_STYLE,
              onClick: function () { onInsert(chip.name); },
            }, t("ji-filable.chip.insert")));
          }
          return React.createElement("div", {
            key: chip.id,
            style: Object.assign({}, CHIP_ITEM_STYLE, chip.status === "error" ? CHIP_ERR_STYLE : {}, done ? CHIP_DONE_STYLE : {}),
          }, rows);
        }));
    }

    // ── drop capture ──────────────────────────────────────────────────────
    function getCurrentSession(sessions) {
      try {
        var snapshot = sessions.list.getSnapshot();
        return snapshot && snapshot.current;
      } catch (error) { return undefined; }
    }

    // Insert an `@file` mention into the current session's composer draft.
    // Mirrors the internal QueueDock pattern: resolve the session-scoped ctx,
    // then conversation.input.for(actx).setDraft(...). Best-effort: any
    // resolution failure or non-'plain' phase aborts silently.
    function insertRef(ctx, name) {
      var sessions = ctx.get('sessions') || ctx.sessions;
      if (!sessions) return;
      var sid = getCurrentSession(sessions);
      if (sid === undefined || sid === "") return;
      var actx = sessions.scope(sid);
      if (!actx) return;
      try {
        var conversation = actx.get('conversation');
        if (!conversation) return;
        var input = conversation.input.for(actx);
        var state = input.state.getSnapshot();
        if (!state || state.phase !== 'plain') return;
        var ref = sessionfilesRef(name);
        if (ref === null || ref === undefined) return;
        input.setDraft(appendRef(state.draft, ref));
      } catch (error) { /* insert is best-effort */ }
    }

    function uploadFile(sessionId, file) {
      return file.arrayBuffer()
        .then(function (buffer) { return crypto.subtle.digest("SHA-256", buffer); })
        .then(function (digest) {
          var hex = Array.from(new Uint8Array(digest)).map(function (b) { return b.toString(16).padStart(2, "0"); }).join("");
          return fetch(buildUploadUrl(sessionId, file.name), {
            method: "POST",
            headers: { "x-sha256": hex },
            body: file,
          });
        })
        .then(function (response) {
          return response.json().catch(function () { return {}; }).then(function (body) {
            if (!response.ok || body.ok !== true) {
              var error = new Error((body && body.error) || ("HTTP " + String(response.status)));
              error.code = (body && body.error) || "";
              throw error;
            }
            return body.file || {};
          });
        });
    }

    function handleDrop(ctx, sessions, dataTransfer) {
      var items = Array.from(dataTransfer.items || []);
      var hasDirectory = items.some(function (item) {
        var entry = item.webkitGetAsEntry ? item.webkitGetAsEntry() : null;
        return Boolean(entry && entry.isDirectory);
      });
      if (hasDirectory) return Promise.resolve(); // directories are silently ignored
      var plan = planUploads(Array.from(dataTransfer.files || []));
      if (plan.takeOver.length === 0) return Promise.resolve(); // pure whitelisted images → existing flow
      var t = ctx.locale.bind(NS);
      var sid = getCurrentSession(sessions);
      if (sid === undefined || sid === "") {
        toast(t("ji-filable.drag.noSession"), false);
        return Promise.resolve();
      }
      var skippedImages = plan.skippedImages;
      var okCount = 0;
      var errors = [];
      var workspaceUnknown = false;
      var chain = Promise.resolve();
      plan.takeOver.forEach(function (file) {
        chain = chain.then(function () {
          var chipId = addChip({ name: file.name, size: file.size });
          return uploadFile(sid, file).then(function (fileInfo) {
            okCount += 1;
            updateChip(chipId, { status: "done", name: fileInfo.name || file.name, size: fileInfo.size || file.size });
          }, function (error) {
            if (error && error.code === "session workspace unknown") workspaceUnknown = true;
            errors.push(file.name + ": " + String((error && error.message) || error));
            updateChip(chipId, { status: "error" });
          });
        });
      });
      return chain.then(function () {
        if (errors.length === 0) {
          toast(skippedImages > 0
            ? t("ji-filable.drag.mixedDone", { count: okCount, img: skippedImages })
            : t("ji-filable.drag.done", { count: okCount }), true);
        } else if (workspaceUnknown && errors.length === plan.takeOver.length) {
          toast(t("ji-filable.drag.noWorkspace"), false);
        } else {
          toast(t("ji-filable.drag.partial", { ok: okCount, err: errors[0] }), false);
        }
      });
    }

    function attachDrop(ctx) {
      var sessions = ctx.sessions;
      // Suppress the composer's image-only drop hint for non-image drags when
      // item types are visible; drop-time classification via files is final.
      function suppressNonImage(dataTransfer) {
        var types = dragTypes(dataTransfer);
        if (types.length === 0) return false;
        return classifyBatch(types) !== "all-images";
      }
      function currentSessionId() { return getCurrentSession(sessions); }
      function onDragEnter(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        if (!suppressNonImage(event.dataTransfer)) return; // images/unknown → composer hint
        dropHintDepth += 1;
        var sid = currentSessionId();
        showDropHint(sid === undefined || sid === "");
        event.stopPropagation();
      }
      function onDragOver(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";
        if (!suppressNonImage(event.dataTransfer)) return;
        var sid = currentSessionId();
        showDropHint(sid === undefined || sid === "");
        event.stopPropagation();
      }
      function onDragLeave(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        dropHintDepth = Math.max(0, dropHintDepth - 1);
        // Leaving the window: an OS file drag has no page dragstart, so dragend
        // never fires — a document-level dragleave carries relatedTarget null
        // when the pointer leaves the document. Use that as the reliable hide
        // signal, with depth-0 + out-of-viewport as a backup.
        var leftViewport = event.clientX <= 0 || event.clientY <= 0 || event.clientX >= window.innerWidth || event.clientY >= window.innerHeight;
        if (event.relatedTarget === null || (leftViewport && dropHintDepth === 0)) hideDropHint();
      }
      function onDrop(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        var files = Array.from(event.dataTransfer.files || []);
        var batch = classifyBatch(files.map(function (file) { return file.type; }));
        if (batch === "all-images") return; // existing flow handles it
        event.preventDefault();
        event.stopPropagation();
        hideDropHint();
        handleDrop(ctx, sessions, event.dataTransfer).catch(function (error) {
          toast(String((error && error.message) || error), false);
        });
        // Reset any composer overlay state left over from a drag we captured:
        // its window-level dragend listener clears dragActive.
        try { window.dispatchEvent(new DragEvent("dragend")); } catch (error) { /* best-effort */ }
      }
      function onWindowDragEnd() { hideDropHint(); }
      document.addEventListener("dragenter", onDragEnter, true);
      document.addEventListener("dragover", onDragOver, true);
      document.addEventListener("drop", onDrop, true);
      document.addEventListener("dragleave", onDragLeave, true);
      window.addEventListener("dragend", onWindowDragEnd);
      return function () {
        document.removeEventListener("dragenter", onDragEnter, true);
        document.removeEventListener("dragover", onDragOver, true);
        document.removeEventListener("drop", onDrop, true);
        document.removeEventListener("dragleave", onDragLeave, true);
        window.removeEventListener("dragend", onWindowDragEnd);
      };
    }

    // ── plugin wiring ─────────────────────────────────────────────────────
    var inject = ["slots", "sessions", "locale"];

    function apply(ctx) {
      ctx.effect(function () { return ctx.locale.register(NS, { zh: zh, en: en }); }, "ji-filable: dictionaries");
      ctx.effect(function () { return attachDrop(ctx); }, "ji-filable: drop capture");
      ctx.effect(function () {
        return function () {
          pendingTimers.forEach(clearTimeout);
          pendingTimers.clear();
        };
      }, "ji-filable: timers");
      // Inject the fade keyframes used by the drop hint mask (reversible).
      ctx.effect(function () {
        var style = document.createElement("style");
        style.textContent = "@keyframes dshHintFade { from { opacity: 0; } to { opacity: 1; } }";
        document.head.appendChild(style);
        return function () { document.head.removeChild(style); };
      }, "ji-filable: hint css");

      // Chips are session-scoped: clear them when the active session changes.
      var lastChipSession = null;
      ctx.effect(function () {
        return ctx.sessions.list.subscribe(function () {
          var current = getCurrentSession(ctx.sessions);
          if (lastChipSession !== null && current !== lastChipSession) clearChips();
          lastChipSession = current;
        });
      }, "ji-filable: chip session watch");

      ctx.slots.inject("shell.overlay", function () {
        return ctx.slots.register({ name: "shell.overlay", id: "ji-filable-toast" }, function () {
          return React.createElement(ToastStack, { t: ctx.locale.bind(NS) });
        });
      });

      ctx.slots.inject("shell.overlay", function () {
        return ctx.slots.register({ name: "shell.overlay", id: "ji-filable-drop-hint" }, function () {
          return React.createElement(DropHintOverlay, { t: ctx.locale.bind(NS) });
        });
      });

      ctx.slots.inject("conversation.input.dock", function () {
        return ctx.slots.register({ name: "conversation.input.dock", id: "ji-filable-files", order: 25 }, function () {
          return React.createElement(ChipRow, { t: ctx.locale.bind(NS), onInsert: function (name) { insertRef(ctx, name); }, onRemove: function (id) { removeChip(id); } });
        });
      });
    }

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  },
});
