// JI-Filable — browser half (client plugin bundle).
// GENERATED by scripts/build-client.mjs from this template + lib/drop-logic.js
// — do not edit lib/client.js by hand; edit this file and drop-logic.js.
// The pure decision/store logic is inlined below (from lib/drop-logic.js) so
// the tested module is byte-identical to what runs here.
window.__ModuleLoader__.load({
  id: "ji-filable",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    var React = require("react");

    // ── pure drop-decision + store logic (inlined from lib/drop-logic.js) ──
// JI-Filable — browser drop-decision logic (pure, testable, single source of
// truth). The client bundle inlines these same small functions because the
// module loader only resolves table words, not sibling files; this module is
// what the unit tests pin.

/** The four image media types the built-in attachment flow accepts. */
const IMAGE_WHITELIST = ['image/png', 'image/jpeg', 'image/webp', 'image/gif']

/**
 * Classify a dropped file's MIME type: whitelisted images keep the existing
 * attachment flow; everything else (including svg/tiff/bmp/heic and any
 * non-image type) is taken over by ji-filable.
 * @returns 'pass' | 'take-over'
 */
function classifyFile(fileType) {
  return IMAGE_WHITELIST.includes(fileType) ? 'pass' : 'take-over'
}

/**
 * Build the upload request URL with URL-encoded query parameters.
 * @param {string} sessionId
 * @param {string} name
 */
function buildUploadUrl(sessionId, name) {
  const params = new URLSearchParams()
  if (sessionId !== '') params.set('session', sessionId)
  params.set('name', name)
  return `/ji-filable/files?${params.toString()}`
}

/** Whether a drag event carries files at all (text/html drags pass through). */
function isFileDrag(dataTransfer) {
  return Boolean(dataTransfer) && Array.from(dataTransfer.types).includes('Files')
}

/**
 * Classify a whole dropped batch by MIME types.
 * @param {Array<string>} fileTypes
 * @returns 'all-images' | 'all-others' | 'mixed'
 */
function classifyBatch(fileTypes) {
  const types = Array.from(fileTypes || [])
  if (types.length === 0) return 'all-others'
  const hasImage = types.some(type => IMAGE_WHITELIST.includes(type))
  const hasOther = types.some(type => !IMAGE_WHITELIST.includes(type))
  if (hasImage && hasOther) return 'mixed'
  return hasImage ? 'all-images' : 'all-others'
}

/**
 * Collect the MIME types visible on a DataTransfer before drop. Chrome exposes
 * item.type on dragenter/dragover; when nothing is visible yet the caller must
 * fall back to drop-time classification via dataTransfer.files.
 * @returns {Array<string>}
 */
function dragTypes(dataTransfer) {
  const items = dataTransfer && dataTransfer.items ? Array.from(dataTransfer.items) : []
  return items
    .map(item => (item && typeof item.type === 'string' ? item.type : ''))
    .filter(type => type !== '')
}

/** Human-readable byte size ("1.2 MB"). */
function formatBytes(value) {
  const n = Number(value)
  if (typeof n !== 'number' || !Number.isFinite(n) || n <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB']
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)))
  const v = n / Math.pow(1024, i)
  return `${v >= 100 ? Math.round(v) : v.toFixed(1)} ${units[i]}`
}

/**
 * Minimal subscription store — the single state mechanism behind toasts and
 * chips (one tested implementation, one React bridge).
 * @returns {{get: () => T, set: (next: T) => void, subscribe: (l: (v: T) => void) => () => void}}
 */
function subscribeStore(initial) {
  let value = initial
  const listeners = new Set()
  return {
    get: () => value,
    set(next) {
      value = next
      listeners.forEach(listener => listener(value))
    },
    subscribe(listener) {
      listeners.add(listener)
      return () => { listeners.delete(listener) }
    },
  }
}

/**
 * Plan a dropped batch: split into the files ji-filable takes over and the
 * whitelisted images that keep the existing flow.
 * @param {Array<{type: string}>} files
 * @returns {{takeOver: Array<{type: string}>, skippedImages: number}}
 */
function planUploads(files) {
  const all = Array.from(files || [])
  const takeOver = all.filter(file => classifyFile(file.type) === 'take-over')
  return { takeOver, skippedImages: all.length - takeOver.length }
}

    var NS = "ji-filable";
    var zh = {
      "ji-filable.chip.uploading": "上传中",
      "ji-filable.chip.done": "已就绪",
      "ji-filable.chip.error": "失败",
      "ji-filable.drag.noSession": "请先打开一个会话，再拖入文件",
      "ji-filable.drag.noWorkspace": "无法确定会话工作区，文件未保存",
      "ji-filable.drag.done": "已上传 {count} 个文件到工作区 sessionfiles",
      "ji-filable.drag.mixedDone": "已上传 {count} 个文件（{img} 张图片已跳过，请单独拖入以使用视觉流程）",
      "ji-filable.drag.partial": "上传完成 {ok} 个，失败: {err}",
    };
    var en = {
      "ji-filable.chip.uploading": "Uploading",
      "ji-filable.chip.done": "Ready",
      "ji-filable.chip.error": "Failed",
      "ji-filable.drag.noSession": "Open a session before dropping files",
      "ji-filable.drag.noWorkspace": "Session workspace unknown — file not saved",
      "ji-filable.drag.done": "Uploaded {count} file(s) to workspace sessionfiles",
      "ji-filable.drag.mixedDone": "Uploaded {count} file(s) ({img} image(s) skipped — drop images alone to use the vision flow)",
      "ji-filable.drag.partial": "Uploaded {ok}, failed: {err}",
    };

    // ── toast store (subscribeStore; timers tracked for fiber cleanup) ─────
    var toasts = subscribeStore([]);
    var toastSeq = 0;
    var pendingTimers = new Set();
    var TOAST_STYLE = { position: "fixed", right: "16px", bottom: "16px", display: "flex", flexDirection: "column", gap: "8px", zIndex: 9999, pointerEvents: "none" };
    var TOAST_ITEM = { padding: "10px 14px", borderRadius: "8px", fontSize: "13px", maxWidth: "320px", boxShadow: "0 4px 16px rgba(0,0,0,.18)", color: "#fff", pointerEvents: "auto" };
    function toast(text, ok) {
      var id = ++toastSeq;
      toasts.set(toasts.get().concat([{ id: id, text: String(text), ok: ok !== false }]));
      var handle = setTimeout(function () {
        pendingTimers.delete(handle);
        toasts.set(toasts.get().filter(function (t) { return t.id !== id; }));
      }, 4000);
      pendingTimers.add(handle);
    }

    // ── chip store (display-only, session-scoped) ──────────────────────────
    var chips = subscribeStore([]);
    var chipSeq = 0;
    var CHIP_ROW_STYLE = { display: "flex", flexWrap: "wrap", gap: "8px", padding: "0 2px 2px", boxSizing: "border-box" };
    var CHIP_ITEM_STYLE = { display: "flex", alignItems: "center", gap: "8px", padding: "6px 10px", borderRadius: "8px", border: "1px solid var(--dsw-alias-border-l2)", background: "var(--dsw-alias-bg-layer-1)", color: "var(--dsw-alias-label-primary)", fontSize: "12px", maxWidth: "320px" };
    var CHIP_ERR_STYLE = { borderColor: "var(--dsw-state-error-primary, #d9534f)" };
    var CHIP_NAME_STYLE = { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" };
    var CHIP_META_STYLE = { color: "var(--dsw-alias-label-secondary)", whiteSpace: "nowrap" };
    function addChip(entry) {
      var id = ++chipSeq;
      chips.set(chips.get().concat([Object.assign({ id: id, status: "uploading" }, entry)]));
      return id;
    }
    function updateChip(id, patch) {
      chips.set(chips.get().map(function (chip) { return chip.id === id ? Object.assign({}, chip, patch) : chip; }));
    }
    function clearChips() { chips.set([]); }

    function ToastStack(props) {
      var t = props.t;
      var state = React.useState(toasts.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return toasts.subscribe(setItems); }, []);
      return React.createElement("div", { style: TOAST_STYLE },
        items.map(function (item) {
          return React.createElement("div", {
            key: item.id,
            style: Object.assign({}, TOAST_ITEM, { background: item.ok ? "#2f7d4d" : "#c0392b" }),
          }, item.text);
        }));
    }

    function ChipRow(props) {
      var t = props.t;
      var state = React.useState(chips.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return chips.subscribe(setItems); }, []);
      if (items.length === 0) return null;
      return React.createElement("div", { style: CHIP_ROW_STYLE },
        items.map(function (chip) {
          return React.createElement("div", {
            key: chip.id,
            style: Object.assign({}, CHIP_ITEM_STYLE, chip.status === "error" ? CHIP_ERR_STYLE : {}),
          },
            React.createElement("span", { style: CHIP_NAME_STYLE }, chip.name),
            React.createElement("span", { style: CHIP_META_STYLE },
              formatBytes(chip.size) + " · " + (chip.status === "uploading" ? t("ji-filable.chip.uploading") : chip.status === "error" ? t("ji-filable.chip.error") : t("ji-filable.chip.done"))),
          );
        }));
    }

    // ── drop capture ──────────────────────────────────────────────────────
    function getCurrentSession(sessions) {
      try {
        var snapshot = sessions.list.getSnapshot();
        return snapshot && snapshot.current;
      } catch (error) { return undefined; }
    }

    function uploadFile(sessionId, file) {
      return file.arrayBuffer()
        .then(function (buffer) { return crypto.subtle.digest("SHA-256", buffer); })
        .then(function (digest) {
          var hex = Array.from(new Uint8Array(digest)).map(function (b) { return b.toString(16).padStart(2, "0"); }).join("");
          return fetch(buildUploadUrl(sessionId, file.name), {
            method: "POST",
            headers: { "x-sha256": hex },
            body: file,
          });
        })
        .then(function (response) {
          return response.json().catch(function () { return {}; }).then(function (body) {
            if (!response.ok || body.ok !== true) {
              var error = new Error((body && body.error) || ("HTTP " + String(response.status)));
              error.code = (body && body.error) || "";
              throw error;
            }
            return body.file || {};
          });
        });
    }

    function handleDrop(ctx, sessions, dataTransfer) {
      var items = Array.from(dataTransfer.items || []);
      var hasDirectory = items.some(function (item) {
        var entry = item.webkitGetAsEntry ? item.webkitGetAsEntry() : null;
        return Boolean(entry && entry.isDirectory);
      });
      if (hasDirectory) return Promise.resolve(); // directories are silently ignored
      var plan = planUploads(Array.from(dataTransfer.files || []));
      if (plan.takeOver.length === 0) return Promise.resolve(); // pure whitelisted images → existing flow
      var t = ctx.locale.bind(NS);
      var sid = getCurrentSession(sessions);
      if (sid === undefined || sid === "") {
        toast(t("ji-filable.drag.noSession"), false);
        return Promise.resolve();
      }
      var skippedImages = plan.skippedImages;
      var okCount = 0;
      var errors = [];
      var workspaceUnknown = false;
      var chain = Promise.resolve();
      plan.takeOver.forEach(function (file) {
        chain = chain.then(function () {
          var chipId = addChip({ name: file.name, size: file.size });
          return uploadFile(sid, file).then(function (fileInfo) {
            okCount += 1;
            updateChip(chipId, { status: "done", name: fileInfo.name || file.name, size: fileInfo.size || file.size });
          }, function (error) {
            if (error && error.code === "session workspace unknown") workspaceUnknown = true;
            errors.push(file.name + ": " + String((error && error.message) || error));
            updateChip(chipId, { status: "error" });
          });
        });
      });
      return chain.then(function () {
        if (errors.length === 0) {
          toast(skippedImages > 0
            ? t("ji-filable.drag.mixedDone", { count: okCount, img: skippedImages })
            : t("ji-filable.drag.done", { count: okCount }), true);
        } else if (workspaceUnknown && errors.length === plan.takeOver.length) {
          toast(t("ji-filable.drag.noWorkspace"), false);
        } else {
          toast(t("ji-filable.drag.partial", { ok: okCount, err: errors[0] }), false);
        }
      });
    }

    function attachDrop(ctx) {
      var sessions = ctx.sessions;
      // Suppress the composer's image-only drop hint for non-image drags when
      // item types are visible; drop-time classification via files is final.
      function suppressNonImage(dataTransfer) {
        var types = dragTypes(dataTransfer);
        if (types.length === 0) return false;
        return classifyBatch(types) !== "all-images";
      }
      function onDragEnter(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        if (suppressNonImage(event.dataTransfer)) event.stopPropagation();
      }
      function onDragOver(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";
        if (suppressNonImage(event.dataTransfer)) event.stopPropagation();
      }
      function onDrop(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        var files = Array.from(event.dataTransfer.files || []);
        var batch = classifyBatch(files.map(function (file) { return file.type; }));
        if (batch === "all-images") return; // existing flow handles it
        event.preventDefault();
        event.stopPropagation();
        handleDrop(ctx, sessions, event.dataTransfer).catch(function (error) {
          toast(String((error && error.message) || error), false);
        });
        // Reset any composer overlay state left over from a drag we captured:
        // its window-level dragend listener clears dragActive.
        try { window.dispatchEvent(new DragEvent("dragend")); } catch (error) { /* best-effort */ }
      }
      document.addEventListener("dragenter", onDragEnter, true);
      document.addEventListener("dragover", onDragOver, true);
      document.addEventListener("drop", onDrop, true);
      return function () {
        document.removeEventListener("dragenter", onDragEnter, true);
        document.removeEventListener("dragover", onDragOver, true);
        document.removeEventListener("drop", onDrop, true);
      };
    }

    // ── plugin wiring ─────────────────────────────────────────────────────
    var inject = ["slots", "sessions", "locale"];

    function apply(ctx) {
      ctx.effect(function () { return ctx.locale.register(NS, { zh: zh, en: en }); }, "ji-filable: dictionaries");
      ctx.effect(function () { return attachDrop(ctx); }, "ji-filable: drop capture");
      ctx.effect(function () {
        return function () {
          pendingTimers.forEach(clearTimeout);
          pendingTimers.clear();
        };
      }, "ji-filable: timers");

      // Chips are session-scoped: clear them when the active session changes.
      var lastChipSession = null;
      ctx.effect(function () {
        return ctx.sessions.list.subscribe(function () {
          var current = getCurrentSession(ctx.sessions);
          if (lastChipSession !== null && current !== lastChipSession) clearChips();
          lastChipSession = current;
        });
      }, "ji-filable: chip session watch");

      ctx.slots.inject("shell.overlay", function () {
        return ctx.slots.register({ name: "shell.overlay", id: "ji-filable-toast" }, function () {
          return React.createElement(ToastStack, { t: ctx.locale.bind(NS) });
        });
      });

      ctx.slots.inject("conversation.input.dock", function () {
        return ctx.slots.register({ name: "conversation.input.dock", id: "ji-filable-files", order: 25 }, function () {
          return React.createElement(ChipRow, { t: ctx.locale.bind(NS) });
        });
      });
    }

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  },
});
