// JI-Filable — browser half (client plugin bundle).
// GENERATED by scripts/build-client.mjs from this template + lib/drop-logic.js
// — do not edit lib/client.js by hand; edit this file and drop-logic.js.
// The pure decision/store logic is inlined below (from lib/drop-logic.js) so
// the tested module is byte-identical to what runs here.
window.__ModuleLoader__.load({
  id: "ji-filable",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
    var React = require("react");

    // ── pure drop-decision + store logic (inlined from lib/drop-logic.js) ──
// JI-Filable — browser drop-decision logic (pure, testable, single source of
// truth). The client bundle inlines these same small functions because the
// module loader only resolves table words, not sibling files; this module is
// what the unit tests pin.
//
// Every dropped file is taken over, images included: they all land in the
// session's `sessionfiles/` dir, so no MIME split exists any more.

/**
 * Build the upload request URL with URL-encoded query parameters.
 * @param {string} sessionId
 * @param {string} name
 */
function buildUploadUrl(sessionId, name) {
  const params = new URLSearchParams()
  if (sessionId !== '') params.set('session', sessionId)
  params.set('name', name)
  return `/ji-filable/files?${params.toString()}`
}

/** Whether a drag event carries files at all (text/html drags pass through). */
function isFileDrag(dataTransfer) {
  return Boolean(dataTransfer) && Array.from(dataTransfer.types).includes('Files')
}

/**

/** Human-readable byte size ("1.2 MB"). */
function formatBytes(value) {
  const n = Number(value)
  if (typeof n !== 'number' || !Number.isFinite(n) || n <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB']
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)))
  const v = n / Math.pow(1024, i)
  return `${v >= 100 ? Math.round(v) : v.toFixed(1)} ${units[i]}`
}

/**
 * Minimal subscription store — the single state mechanism behind toasts and
 * chips (one tested implementation, one React bridge).
 * @returns {{get: () => T, set: (next: T) => void, subscribe: (l: (v: T) => void) => () => void}}
 */
function subscribeStore(initial) {
  let value = initial
  const listeners = new Set()
  return {
    get: () => value,
    set(next) {
      value = next
      listeners.forEach(listener => listener(value))
    },
    subscribe(listener) {
      listeners.add(listener)
      return () => { listeners.delete(listener) }
    },
  }
}

/**
/**
 * Plan a dropped batch: every file is taken over (no MIME split) and returned
 * in request order.
 * @param {Array<{type: string}>} files
 * @returns {{takeOver: Array<{type: string}>}}
 */
function planUploads(files) {
  return { takeOver: Array.from(files || []) }
}

/**
 * Format an `@file` mention for a path under the workspace `sessionfiles/`
 * dir, following the native @-reference grammar: `@path` normally, `@"path"`
 * when the path contains whitespace. Returns null for a path the grammar
 * cannot represent safely (control chars / a stray quote).
 * @param {string} name - the final (deduped) filename on disk.
 * @returns {string | null}
 */
function sessionfilesRef(name) {
  const path = 'sessionfiles/' + String(name)
  if (/[\u0000-\u001f\u007f-\u009f"]/.test(path)) return null
  return /\s/.test(path) ? `@"${path}"` : `@${path}`
}

/**
 * Append a reference to an existing draft, inserting a single space separator
 * only when the draft is non-empty and does not already end in whitespace.
 * @param {string} draft - current composer draft.
 * @param {string} ref - the reference text to append.
 * @returns {string}
 */
function appendRef(draft, ref) {
  const d = String(draft || '')
  const sep = d === '' || /\s$/.test(d) ? '' : ' '
  return d + sep + ref
}

    var NS = "ji-filable";
    var zh = {
      "ji-filable.chip.uploading": "上传中",
      "ji-filable.chip.done": "已就绪",
      "ji-filable.chip.error": "失败",
      "ji-filable.chip.insert": "插入 @地址",
      "ji-filable.chip.close": "关闭",
      "ji-filable.drag.noSession": "请先打开一个会话，再拖入文件",
      "ji-filable.drag.noWorkspace": "无法确定会话工作区，文件未保存",
      "ji-filable.drag.done": "已上传 {count} 个文件到工作区 sessionfiles",
      "ji-filable.drag.partial": "上传完成 {ok} 个，失败: {err}",
      "ji-filable.dropHint.title": "拖入图片或文件",
      "ji-filable.dropHint.desc": "松开即保存到工作区 sessionfiles",
      "ji-filable.dropHint.noSession": "先打开一个会话，再拖入图片或文件",
    };
    var en = {
      "ji-filable.chip.uploading": "Uploading",
      "ji-filable.chip.done": "Ready",
      "ji-filable.chip.error": "Failed",
      "ji-filable.chip.insert": "Insert @ref",
      "ji-filable.chip.close": "Close",
      "ji-filable.drag.noSession": "Open a session before dropping files",
      "ji-filable.drag.noWorkspace": "Session workspace unknown — file not saved",
      "ji-filable.drag.done": "Uploaded {count} file(s) to workspace sessionfiles",
      "ji-filable.drag.partial": "Uploaded {ok}, failed: {err}",
      "ji-filable.dropHint.title": "Drop images or files",
      "ji-filable.dropHint.desc": "Release to save into workspace sessionfiles",
      "ji-filable.dropHint.noSession": "Open a session before dropping images or files",
    };

    // ── toast store (subscribeStore; timers tracked for fiber cleanup) ─────
    var toasts = subscribeStore([]);
    var toastSeq = 0;
    var pendingTimers = new Set();
    var TOAST_STYLE = { position: "fixed", right: "16px", bottom: "16px", display: "flex", flexDirection: "column", gap: "8px", zIndex: 9999, pointerEvents: "none" };
    var TOAST_ITEM = { padding: "10px 14px", borderRadius: "8px", fontSize: "13px", maxWidth: "320px", boxShadow: "0 4px 16px rgba(0,0,0,.18)", color: "#fff", pointerEvents: "auto" };
    function toast(text, ok) {
      var id = ++toastSeq;
      toasts.set(toasts.get().concat([{ id: id, text: String(text), ok: ok !== false }]));
      var handle = setTimeout(function () {
        pendingTimers.delete(handle);
        toasts.set(toasts.get().filter(function (t) { return t.id !== id; }));
      }, 4000);
      pendingTimers.add(handle);
    }

    // ── chip store (display-only, session-scoped) ──────────────────────────
    var chips = subscribeStore([]);
    var chipSeq = 0;
    var CHIP_ROW_STYLE = { display: "flex", flexWrap: "wrap", gap: "8px", padding: "0 2px 2px", boxSizing: "border-box" };
    var CHIP_ITEM_STYLE = { display: "flex", alignItems: "center", gap: "8px", padding: "6px 10px", borderRadius: "8px", border: "1px solid var(--dsw-alias-border-l2)", background: "var(--dsw-alias-bg-layer-1)", color: "var(--dsw-alias-label-primary)", fontSize: "12px", maxWidth: "320px" };
    var CHIP_ERR_STYLE = { borderColor: "var(--dsw-state-error-primary, #d9534f)" };
    var CHIP_NAME_STYLE = { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" };
    var CHIP_META_STYLE = { color: "var(--dsw-alias-label-secondary)", whiteSpace: "nowrap" };
    var CHIP_DONE_STYLE = { cursor: "pointer" };
    var CHIP_INSERT_STYLE = { marginLeft: "6px", padding: "2px 8px", borderRadius: "6px", border: "1px solid var(--dsw-alias-border-l2)", background: "var(--dsw-alias-bg-layer-2)", color: "var(--dsw-alias-label-primary)", fontSize: "12px", cursor: "pointer", flex: "none" };
    var CHIP_CLOSE_STYLE = { flex: "none", border: "none", background: "transparent", color: "var(--dsw-alias-label-tertiary)", cursor: "pointer", fontSize: "14px", lineHeight: "1", padding: "2px 4px", borderRadius: "4px" };
    var CHIP_CLOSE_HOVER = { background: "var(--dsw-alias-bg-layer-2)", color: "var(--dsw-alias-label-primary)" };
    function addChip(entry) {
      var id = ++chipSeq;
      chips.set(chips.get().concat([Object.assign({ id: id, status: "uploading" }, entry)]));
      return id;
    }
    function updateChip(id, patch) {
      chips.set(chips.get().map(function (chip) { return chip.id === id ? Object.assign({}, chip, patch) : chip; }));
    }
    function clearChips() { chips.set([]); }
    function removeChip(id) {
      chips.set(chips.get().filter(function (chip) { return chip.id !== id; }));
    }

    // ── drop hint store (full-viewport overlay while dragging any file) ───
    // Same look as the built-in composer overlay (DropOverlay.module.css +
    // its two illustrations), so a drop reads identically whichever half
    // would have taken it. Styles live in HINT_CSS, injected below.
    var dropHint = subscribeStore({ visible: false, disabled: false });
    var dropHintDepth = 0;
    function showDropHint(disabled) { dropHint.set({ visible: true, disabled: Boolean(disabled) }); }
    function hideDropHint() { dropHintDepth = 0; dropHint.set({ visible: false, disabled: false }); }
    function DropHintOverlay(props) {
      var t = props.t;
      var state = React.useState(dropHint.get());
      var value = state[0];
      var setValue = state[1];
      React.useEffect(function () { return dropHint.subscribe(setValue); }, []);
      if (!value.visible) return null;
      var illustration = value.disabled ? HINT_ILLUSTRATION_BLOCKED : HINT_ILLUSTRATION;
      return React.createElement("div", { className: "ji-filable-hint-mask", role: "status" },
        React.createElement("div", { className: "ji-filable-hint-wrap" },
          React.createElement("div", {
            className: "ji-filable-hint-illustration",
            "aria-hidden": "true",
            dangerouslySetInnerHTML: { __html: illustration },
          }),
          React.createElement("div", { className: "ji-filable-hint-title" }, value.disabled ? t("ji-filable.dropHint.noSession") : t("ji-filable.dropHint.title")),
          value.disabled ? null : React.createElement("div", { className: "ji-filable-hint-desc" }, t("ji-filable.dropHint.desc")),
        ));
    }
    // The built-in overlay's two illustrations (115x84), inlined as markup so
    // the component above stays a plain createElement tree. Clip id is renamed
    // so it can coexist with the official one.
    var HINT_ILLUSTRATION = '<svg width="115" height="84" viewBox="0 0 115 84" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#jiFilableHintClip)"><rect y="17.0742" width="44.1832" height="43.6431" rx="12" transform="rotate(-22.7338 0 17.0742)" fill="#9CE5ED"/><rect x="73.4043" y="8.54297" width="43.7267" height="50.5284" rx="8" transform="rotate(17.403 73.4043 8.54297)" fill="#679EFE"/><path d="M30.4917 28.1369L40.8865 33.4564L37.2232 34.9524L29.5302 31.0159L26.7919 39.2122L23.1285 40.7082L26.8287 29.6338L16.8967 24.5516L20.5601 23.0556L27.7902 26.7549L30.3639 19.052L34.0273 17.556L30.4917 28.1369Z" fill="white"/><path d="M77.5088 26.3047L101.057 33.7966" stroke="white" stroke-width="3"/><path d="M72.2646 42.7871L86.3938 47.2823" stroke="white" stroke-width="3"/><path d="M74.8867 34.5469L98.4353 42.0388" stroke="white" stroke-width="3"/><rect x="31.583" y="38.6641" width="44.9157" height="44.3666" rx="12" transform="rotate(-0.134233 31.583 38.6641)" fill="#3964FE"/><path d="M38.9521 73.0337C39.6129 71.7086 41.7113 66.0937 43.5113 61.1663C44.1607 59.3885 46.7484 59.3923 47.4591 61.1465C48.9728 64.8828 50.7969 68.6922 51.9988 69.1925C54.2946 70.1482 57.9854 59.3573 68.0064 70.1801" stroke="white" stroke-width="3"/><circle cx="60.6157" cy="52.247" r="4.38794" transform="rotate(22.5996 60.6157 52.247)" fill="white"/></g><defs><clipPath id="jiFilableHintClip"><rect width="115" height="84" fill="white"/></clipPath></defs></svg>';
    var HINT_ILLUSTRATION_BLOCKED = '<svg width="115" height="84" viewBox="0 0 115 84" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M29.6829 4.63701L11.0677 12.4368C4.95519 14.998 2.07624 22.0294 4.6374 28.1419L12.2285 46.259C14.7896 52.3715 21.8211 55.2505 27.9336 52.6893L46.5488 44.8895C52.6613 42.3283 55.5403 35.2969 52.9791 29.1844L45.388 11.0673C42.8269 4.9548 35.7954 2.07585 29.6829 4.63701Z" fill="#979DA6"/><path d="M30.4915 28.1375L40.8863 33.4569L37.223 34.9529L29.53 31.0165L26.7917 39.2128L23.1283 40.7088L26.8285 29.6344L16.8965 24.5522L20.5599 23.0562L27.79 26.7555L30.3637 19.0526L34.0271 17.5566L30.4915 28.1375Z" fill="white"/><path d="M107.496 19.2285L81.0381 10.9357C76.8221 9.61423 72.333 11.9607 71.0116 16.1768L60.6844 49.1246C59.363 53.3406 61.7095 57.8297 65.9255 59.1511L92.383 67.4439C96.599 68.7654 101.088 66.4189 102.41 62.2029L112.737 29.255C114.058 25.039 111.712 20.55 107.496 19.2285Z" fill="#979DA6"/><path d="M77.5088 26.3047L101.057 33.7967" stroke="white" stroke-width="3"/><path d="M72.2646 42.7871L86.3938 47.2823" stroke="white" stroke-width="3"/><path d="M74.8867 34.5469L98.4353 42.0388" stroke="white" stroke-width="3"/><path d="M66.5798 30.1418L41.481 30.2006C33.5281 30.2193 27.0962 36.6815 27.1148 44.6343L27.172 69.0742C27.1907 77.0271 33.6529 83.459 41.6057 83.4404L66.7045 83.3816C74.6574 83.363 81.0894 76.9008 81.0707 68.9479L81.0135 44.5081C80.9949 36.5552 74.5327 30.1232 66.5798 30.1418Z" fill="#F59E0B"/><path d="M54 70.7969C61.732 70.7969 68 64.5289 68 56.7969C68 49.0649 61.732 42.7969 54 42.7969C46.268 42.7969 40 49.0649 40 56.7969C40 64.5289 46.268 70.7969 54 70.7969Z" stroke="white" stroke-width="3.5"/><path d="M44 46.7969L64 66.7969" stroke="white" stroke-width="3.5" stroke-linecap="round"/></svg>';
    // Built-in overlay's stylesheet (DropOverlay.module.css), scoped to our
    // own class names; `pointer-events: none` keeps drag targeting below.
    var HINT_CSS = ".ji-filable-hint-mask{position:fixed;inset:0;z-index:1000;display:flex;align-items:center;justify-content:center;pointer-events:none;background-color:var(--dsw-alias-bg-mask-drop);backdrop-filter:blur(10px);animation:jiFilableHintFade 160ms ease-out}"
      + "@keyframes jiFilableHintFade{from{opacity:0}to{opacity:1}}"
      + "@media (prefers-reduced-motion: reduce){.ji-filable-hint-mask{animation:none}}"
      + ".ji-filable-hint-wrap{display:flex;flex-direction:column;align-items:center;margin-top:-3%;padding:0 40px;color:var(--dsw-alias-label-primary);text-align:center}"
      + ".ji-filable-hint-illustration{width:115px;height:84px}"
      + ".ji-filable-hint-title{margin-top:16px;font:var(--dsw-font-l-20)}"
      + ".ji-filable-hint-desc{margin-top:16px;font:var(--dsw-font-s-14);color:var(--dsw-alias-label-tertiary);white-space:pre-wrap}";    function ToastStack(props) {
      var t = props.t;
      var state = React.useState(toasts.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return toasts.subscribe(setItems); }, []);
      return React.createElement("div", { style: TOAST_STYLE },
        items.map(function (item) {
          return React.createElement("div", {
            key: item.id,
            style: Object.assign({}, TOAST_ITEM, { background: item.ok ? "#2f7d4d" : "#c0392b" }),
          }, item.text);
        }));
    }

    // Close (dismiss) button placed at the left edge of a chip. Hover state is
    // tracked per-button so hooks stay inside a stable component (hooks cannot
    // be called inside a .map callback).
    function CloseButton(props) {
      var t = props.t;
      var onRemove = props.onRemove;
      var hover = React.useState(false);
      var isHover = hover[0];
      var setHover = hover[1];
      return React.createElement("button", {
        type: "button",
        "aria-label": t("ji-filable.chip.close"),
        title: t("ji-filable.chip.close"),
        style: Object.assign({}, CHIP_CLOSE_STYLE, isHover ? CHIP_CLOSE_HOVER : {}),
        onMouseEnter: function () { setHover(true); },
        onMouseLeave: function () { setHover(false); },
        onClick: function () { if (onRemove) onRemove(); },
      }, "\u2715");
    }

    function ChipRow(props) {
      var t = props.t;
      var onInsert = props.onInsert;
      var onRemove = props.onRemove;
      var state = React.useState(chips.get());
      var items = state[0];
      var setItems = state[1];
      React.useEffect(function () { return chips.subscribe(setItems); }, []);
      if (items.length === 0) return null;
      return React.createElement("div", { style: CHIP_ROW_STYLE },
        items.map(function (chip) {
          var done = chip.status === "done";
          var statusText = chip.status === "uploading" ? t("ji-filable.chip.uploading") : chip.status === "error" ? t("ji-filable.chip.error") : t("ji-filable.chip.done");
          var rows = [
            React.createElement(CloseButton, { t: t, onRemove: function () { if (onRemove) onRemove(chip.id); } }),
            React.createElement("span", { style: CHIP_NAME_STYLE }, chip.name),
            React.createElement("span", { style: CHIP_META_STYLE }, formatBytes(chip.size) + " · " + statusText),
          ];
          if (done && onInsert) {
            rows.push(React.createElement("button", {
              type: "button",
              style: CHIP_INSERT_STYLE,
              onClick: function () { onInsert(chip.name); },
            }, t("ji-filable.chip.insert")));
          }
          return React.createElement("div", {
            key: chip.id,
            style: Object.assign({}, CHIP_ITEM_STYLE, chip.status === "error" ? CHIP_ERR_STYLE : {}, done ? CHIP_DONE_STYLE : {}),
          }, rows);
        }));
    }

    // ── drop capture ──────────────────────────────────────────────────────
    // The current Session identity for the document-level drop path. DSH
    // 0.1.6-alpha.2 moved "the session on screen" out of the sessions service:
    // its list snapshot no longer carries `current` (multi-instance Sessions
    // made navigation a view-owner concern). The plugin therefore learns the
    // identity from its own session-scoped dock component, which receives it
    // as a prop. The legacy list field stays as the fallback for older hosts.
    var dockSessionId;

    function normalizeSessionId(sid) {
      return sid === undefined || sid === null ? undefined : String(sid);
    }

    /// Record the Session a session-scoped dock component is bound to.
    function setDockSession(sid) {
      var next = normalizeSessionId(sid);
      if (dockSessionId === next) return;
      if (dockSessionId !== undefined) clearChips();
      dockSessionId = next;
    }

    /// Release the binding only while it still belongs to this dock mount.
    function clearDockSession(sid) {
      if (dockSessionId === normalizeSessionId(sid)) setDockSession(undefined);
    }

    function getCurrentSession(sessions) {
      if (dockSessionId !== undefined) return dockSessionId;
      try {
        var snapshot = sessions.list.getSnapshot();
        return snapshot && snapshot.current;
      } catch (error) { return undefined; }
    }

    // Insert a structured `@file` reference chip into the current session's
    // composer draft through the shell's scoped insert-reference event. A chip
    // insert replaces one span, so chips already in the draft survive — unlike
    // setDraft, which rebuilds the whole document from plain text and flattens
    // every existing chip into literal text. Best-effort: a resolution failure,
    // a non-'plain' phase, or a stale-revision CAS miss aborts silently.
    function insertRef(ctx, name) {
      var sessions = ctx.get('sessions') || ctx.sessions;
      if (!sessions) return;
      var sid = getCurrentSession(sessions);
      if (sid === undefined || sid === "") return;
      var actx = sessions.scope(sid);
      if (!actx) return;
      try {
        var conversation = actx.get('conversation');
        if (!conversation) return;
        var input = conversation.input.for(actx);
        var state = input.state.getSnapshot();
        if (!state || state.phase !== 'plain') return;
        var ref = sessionfilesRef(name);
        if (ref === null || ref === undefined) return;
        // TokenSpan carries DETECT coordinates, where an existing chip counts as
        // one U+FFFC while state.draft (clipboard text) expands it to its
        // clipboardText. A collapsed span at the detect end appends the chip.
        var occurrences = state.occurrences || [];
        var expanded = 0;
        for (var i = 0; i < occurrences.length; i++) {
          expanded += occurrences[i].length - 1;
        }
        var at = state.draft.length - expanded;
        if (at < 0) return;
        actx.bail(actx, 'slash/input-insert-reference', {
          // The built-in `reference` source's codec is identity
          // (clipboardText/serialize return the ref), so the chip renders like
          // any other @file chip and the model still receives this exact text.
          reference: {
            source: 'reference',
            ref: ref,
            label: String(name),
            appearance: 'file',
            clipboardText: ref,
          },
          span: { start: at, end: at, draftRev: state.draftRev },
        });
      } catch (error) { /* insert is best-effort */ }
    }

    function uploadFile(sessionId, file) {
      return file.arrayBuffer()
        .then(function (buffer) { return crypto.subtle.digest("SHA-256", buffer); })
        .then(function (digest) {
          var hex = Array.from(new Uint8Array(digest)).map(function (b) { return b.toString(16).padStart(2, "0"); }).join("");
          return fetch(buildUploadUrl(sessionId, file.name), {
            method: "POST",
            headers: { "x-sha256": hex },
            body: file,
          });
        })
        .then(function (response) {
          return response.json().catch(function () { return {}; }).then(function (body) {
            if (!response.ok || body.ok !== true) {
              var error = new Error((body && body.error) || ("HTTP " + String(response.status)));
              error.code = (body && body.error) || "";
              throw error;
            }
            return body.file || {};
          });
        });
    }

    function handleDrop(ctx, sessions, dataTransfer) {
      var items = Array.from(dataTransfer.items || []);
      var hasDirectory = items.some(function (item) {
        var entry = item.webkitGetAsEntry ? item.webkitGetAsEntry() : null;
        return Boolean(entry && entry.isDirectory);
      });
      if (hasDirectory) return Promise.resolve(); // directories are silently ignored
      var plan = planUploads(Array.from(dataTransfer.files || []));
      var t = ctx.locale.bind(NS);
      var sid = getCurrentSession(sessions);
      if (sid === undefined || sid === "") {
        toast(t("ji-filable.drag.noSession"), false);
        return Promise.resolve();
      }
      var okCount = 0;
      var errors = [];
      var workspaceUnknown = false;
      var chain = Promise.resolve();
      plan.takeOver.forEach(function (file) {
        chain = chain.then(function () {
          var chipId = addChip({ name: file.name, size: file.size });
          return uploadFile(sid, file).then(function (fileInfo) {
            okCount += 1;
            updateChip(chipId, { status: "done", name: fileInfo.name || file.name, size: fileInfo.size || file.size });
          }, function (error) {
            if (error && error.code === "session workspace unknown") workspaceUnknown = true;
            errors.push(file.name + ": " + String((error && error.message) || error));
            updateChip(chipId, { status: "error" });
          });
        });
      });
      return chain.then(function () {
        if (errors.length === 0) {
          toast(t("ji-filable.drag.done", { count: okCount }), true);
        } else if (workspaceUnknown && errors.length === plan.takeOver.length) {
          toast(t("ji-filable.drag.noWorkspace"), false);
        } else {
          toast(t("ji-filable.drag.partial", { ok: okCount, err: errors[0] }), false);
        }
      });
    }

    function attachDrop(ctx) {
      var sessions = ctx.sessions;
      // Every file drag is taken over — images included — so the composer's
      // own overlay never appears and only our hint shows.
      function currentSessionId() { return getCurrentSession(sessions); }
      function onDragEnter(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        dropHintDepth += 1;
        var sid = currentSessionId();
        showDropHint(sid === undefined || sid === "");
        event.stopPropagation();
      }
      function onDragOver(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        if (event.dataTransfer) event.dataTransfer.dropEffect = "copy";
        var sid = currentSessionId();
        showDropHint(sid === undefined || sid === "");
        event.stopPropagation();
      }
      function onDragLeave(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        dropHintDepth = Math.max(0, dropHintDepth - 1);
        // Leaving the window: an OS file drag has no page dragstart, so dragend
        // never fires — a document-level dragleave carries relatedTarget null
        // when the pointer leaves the document. Use that as the reliable hide
        // signal, with depth-0 + out-of-viewport as a backup.
        var leftViewport = event.clientX <= 0 || event.clientY <= 0 || event.clientX >= window.innerWidth || event.clientY >= window.innerHeight;
        if (event.relatedTarget === null || (leftViewport && dropHintDepth === 0)) hideDropHint();
      }
      function onDrop(event) {
        if (!isFileDrag(event.dataTransfer)) return;
        event.preventDefault();
        event.stopPropagation();
        hideDropHint();
        handleDrop(ctx, sessions, event.dataTransfer).catch(function (error) {
          toast(String((error && error.message) || error), false);
        });
        // Reset any composer overlay state left over from a drag we captured:
        // its window-level dragend listener clears dragActive.
        try { window.dispatchEvent(new DragEvent("dragend")); } catch (error) { /* best-effort */ }
      }
      function onWindowDragEnd() { hideDropHint(); }
      document.addEventListener("dragenter", onDragEnter, true);
      document.addEventListener("dragover", onDragOver, true);
      document.addEventListener("drop", onDrop, true);
      document.addEventListener("dragleave", onDragLeave, true);
      window.addEventListener("dragend", onWindowDragEnd);
      return function () {
        document.removeEventListener("dragenter", onDragEnter, true);
        document.removeEventListener("dragover", onDragOver, true);
        document.removeEventListener("drop", onDrop, true);
        document.removeEventListener("dragleave", onDragLeave, true);
        window.removeEventListener("dragend", onWindowDragEnd);
      };
    }

    // ── plugin wiring ─────────────────────────────────────────────────────
    var inject = ["slots", "sessions", "locale"];

    function apply(ctx) {
      ctx.effect(function () { return ctx.locale.register(NS, { zh: zh, en: en }); }, "ji-filable: dictionaries");
      ctx.effect(function () { return attachDrop(ctx); }, "ji-filable: drop capture");
      ctx.effect(function () {
        return function () {
          pendingTimers.forEach(clearTimeout);
          pendingTimers.clear();
        };
      }, "ji-filable: timers");
      // Inject the fade keyframes used by the drop hint mask (reversible).
      ctx.effect(function () {
        var style = document.createElement("style");
        style.textContent = HINT_CSS;
        document.head.appendChild(style);
        return function () { document.head.removeChild(style); };
      }, "ji-filable: hint css");

      // Chips are session-scoped: clear them when the active session changes.
      var lastChipSession = null;
      ctx.effect(function () {
        return ctx.sessions.list.subscribe(function () {
          var current = getCurrentSession(ctx.sessions);
          if (lastChipSession !== null && current !== lastChipSession) clearChips();
          lastChipSession = current;
        });
      }, "ji-filable: chip session watch");

      ctx.slots.inject("shell.overlay", function () {
        return ctx.slots.register({ name: "shell.overlay", id: "ji-filable-toast" }, function () {
          return React.createElement(ToastStack, { t: ctx.locale.bind(NS) });
        });
      });

      ctx.slots.inject("shell.overlay", function () {
        return ctx.slots.register({ name: "shell.overlay", id: "ji-filable-drop-hint" }, function () {
          return React.createElement(DropHintOverlay, { t: ctx.locale.bind(NS) });
        });
      });

      ctx.slots.inject("conversation.input.dock", function () {
        return ctx.slots.register({ name: "conversation.input.dock", id: "ji-filable-files", order: 25 }, function (props) {
          // The dock is session-scoped: its props carry the Session identity this
          // composer belongs to. Recording it is what tells the document-level
          // drop handlers which Session is on screen.
          var sid = props && (props.sessionId !== undefined
            ? props.sessionId
            : (props.session && props.session.sessionId));
          React.useEffect(function () {
            setDockSession(sid);
            return function () { clearDockSession(sid); };
          }, [sid]);
          return React.createElement(ChipRow, { t: ctx.locale.bind(NS), onInsert: function (name) { insertRef(ctx, name); }, onRemove: function (id) { removeChip(id); } });
        });
      });
    }

    exports.apply = apply;
    exports.inject = inject;
    return module.exports;
  },
});
